### ISSUE TITLE
TimeEntry-Liste

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#10]
Im Hauptfenster des Toggl Clients möchte ich eine Auflistung der abgeschlossenen TimeEntrys sehen, welche die Beschreibung, die Dauer, die Start- und die Endzeit des TimeEntrys zeigt. Diese Elemente sollen zwischen den einzelnen TimeEntrys visuell aligned sein.

Zeitschätzung: 3

**Comment by leowe** [comment]
Wenn ich alsWenn ich als authentifizierter Nutzer (#3, #7) im Toggl Client in meinem Squeak-Image bin (#1), möchte ich, dass es ein Fenster in der App gibt, wo ich eine Übersicht über alle meine gestoppten Timer habe (#9). Hier sollte ich auch die Beschreibungen der Trackings bearbeiten können (#5). Alle Veränderungen hier sollen mit Toggl gesyncht werden (#2). Schön wäre es, wenn ich die Übersicht sortieren könnte und hier auch mit eine Auswertung anzeigen lassen kann (#12 ).

Zeitschätzung: 7 Stunden

**Comment by stlutz** [comment]
Endzeit mit Uhrzeit
