### ISSUE TITLE
Synchronisierung mit Toggl

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#2]
Ich möchte eine beliebige Aktion im Toggl Client in Squeak ausführen. Ich erwarte dann, dass diese Aktion auch auf meinen anderen Toggl-Clients sichtbar ist (Web, Mobile etc.)

**Comment by ma-ro** [comment]
Wenn ich als authentifizierter Nutzer (#3, #7) im Toggl Client in meinem Squeak-Image bin (#1), dann erwarte ich bei einer beliebigen Aktion im Client, dass diese Aktion auf meinen anderen Toggl-Clients sichtbar ist (Web, Mobile etc.)

Zeitschätzung: 4 Stunden

**Comment by leowe** [comment]
Not specific enough
