### ISSUE TITLE
Online TimeEntries lokal hinzufügen

### ISSUE THREAD

**Issue by stlutz** [hpi-swa-teaching/TogglClient#23]
Als eingeloggter Nutzer, möchte ich einen Sync-Button haben, welcher zu meiner lokalen TimeEntryliste die TimeEntry der letzten 9 Tage meines Online-Accounts hinzufügt. Dadurch werden zuvor synchronisierte TimeEntry nicht erneut erzeugt.

**Comment by phoeinx** [comment]
Refactoring from Task to TimeEntry happened on branch feature/pull-time-entries until this branch is merged, it is recommended to base your feature branches on feature/pull-time-entries.
