### ISSUE TITLE
Login in den Toggl Account

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#3]
Im Window Menu des Toggl Clients möchte ich einen Login-Eintrag sehen, welcher ein Anmeldefenster öffnet, in dem ich mich mit Benutzername und Passwort authentifiziere.

Zeitschätzung: 2 Stunden

**Comment by stlutz** [comment]
Nur 1 Button zum Login

**Comment by leowe** [comment]
Soll bei jedem Mal auf den Button klicken das Fenster zum Accountinformationen geöffnet werden (Stand jetzt)?

**Comment by stlutz** [comment]
Ja.
