### ISSUE TITLE
Timer starten

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#4]

**Comment by phoeinx** [comment]
Wenn ich als authentifizierter Nutzer (#3, #7) im Toggl Client in meinem Squeak-Image bin (#1), dann möchte ich dort (möglichst direkt in der zuerst angezeigten Seite) einen Timer starten können. Das soll nicht abhängig von einer vorherigen Taskbenennung sein, damit ich auch ohne vorherigen Aufwand/Überlegungen schnell einen Timer starten kann und später einen passenden Namen für den TimeEntry eintragen kann. Der Timer soll solange laufen bis ich ihn stoppe.

Zeitschätzung: 3 Stunden
