### ISSUE TITLE
Anleitung für neue Nutzer

### ISSUE THREAD

**Issue by stlutz** [hpi-swa-teaching/TogglClient#45]
Als Squeak-Nutzer der nicht mit dem TogglClient vertraut ist, möchte ich eine einzige Anlaufstelle für Installationsanweisungen, Featurebeschreibungen (inkl. welche erwartbaren Features fehlen) und Bedienungsanleitungen (startup, gängigste Features / Workflow) haben.

**Comment by leowe** [comment]
Bilder sind erwünscht
