### ISSUE TITLE
TimeEntry nachträglich mit Beschreibung versehen / umbennen

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#5]
Wenn ich als authentifizierter Nutzer (#3, #7) im Toggl Client in meinem Squeak Image bin (#1) und die Übersicht über meine Trackings offen habe (#10), dann möchte ich Trackings dort umbenennen können, bzw. auch nachträglich mit einer Beschreibung versehen. So kann ich auch erst Zeit tracken und mir dann einen sinnvollen Namen ausdenken. Ich erwarte, dass diese Umbenennung mit meinem Toggl Account synchronisiert wird und somit auch z.B. in der WebApp von Toggl erscheint (#2).

Zeitschätzung: 3 Stunden

**Comment by phoeinx** [comment]
Wenn ich als authentifizierter Nutzer im Toggl Client in meinem Squeak Image bin und die Übersicht über meine Trackings offen habe, dann möchte ich Trackings dort umbenennen können, bzw. auch nachträglich mit einer Beschreibung versehen. So kann ich auch erst Zeit tracken und mir dann einen sinnvollen Namen ausdenken.
