### ISSUE TITLE
TimeEntry mit Beschreibung starten / stoppen

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#6]
Wenn ich als authentifizierter Nutzer (#3, #6) mich im Toggl Client in meinem Squeak Image befinde (#1), möchte ich dort (möglichst in dem dort zuerst angezeigtem Fenster) ein Tracking direkt mit Beschreibung starten können, d.h. einen Namen eingeben, sowie einen Timer starten, der erst stoppt, wenn ich ihn stoppe. Das Tracking soll nach dem Stoppen in meiner Trackings Übersicht (#10) erscheinen. Ich erwarte, dass dieses Tracking mit meinem Toggl Account synchronisiert ist und somit auch z.B. in der WebApp von Toggl erscheint (#2).

Zeitschätzung: 3 Stunden

**Comment by phoeinx** [comment]
Wenn ich als authentifizierter Nutzer mich im Toggl Client in meinem Squeak Image befinde, möchte ich dort (möglichst in dem dort zuerst angezeigtem Fenster) ein Tracking direkt mit Beschreibung starten können, d.h. einen Namen eingeben, sowie einen Timer starten, der erst stoppt, wenn ich ihn stoppe. Das Tracking soll nach dem Stoppen in meiner Trackings Übersicht (#10) erscheinen.
