### ISSUE TITLE
Logout aus Toggl

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#8]
Ich möchte in meinem Toggl Client (#1) wenn ich bereits eingeloggt bin (#3) die Möglichkeit haben mich wieder auszuloggen um z.B. den Toggl Account zu wechseln. Dafür soll der Login-Button nach dem Einloggen zum LogOut-Button werden. 
Danach sollte ich mich beispielsweise mit einem anderen Toggl Account(#3) oder mit einem API-Token(#7) wieder einloggen können.
Alle mit dem vorherigen Account assoziierten TimeEntries verschwinden dabei aus der Übersicht.
Nach erfolgten Logout ist es nicht mehr möglich auf synchronise zu drücken.

**Comment by Jasperhino** [comment]
Ich möchte in meinem Toggl Client (#1) wenn ich bereits eingeloggt bin (#3) die Möglichkeit haben mich wieder auszuloggen um z.B. den Toggl Account zu wechseln. Danach sollte ich mich beispielsweise mit einem anderen Toggl Account(#3) oder mit einem API-Token(#7) wieder einloggen können.
Alle mit dem vorherigen Account assoziierten TimeEntries verschwinden dabei aus der Übersicht.
