### ISSUE TITLE
TimeEntry stoppen

### ISSUE THREAD

**Issue by jeriox** [hpi-swa-teaching/TogglClient#9]

**Comment by leowe** [comment]
Wenn ich als authentifizierter Nutzer (#3, #7) im Toggl Client in meinem Squeak-Image bin (#1) und einen Timer gestartet habe (#4), dann möchte ich dort (möglichst direkt in der zuerst angezeigten Seite) den aktuell laufenden Timer stoppen können. Ich erwarte, dass nach dem Stoppen des Timers die aufgezeichnete Zeit in der Übersicht (#10) und synchronisiert in der WebApp erscheint (#2).

Zeitschätzung: 2 Stunden

**Comment by leowe** [comment]
divided user story in sub stories
